##
## EPITECH PROJECT, 2019
## firtree
## File description:
## Makefile
##

NAME = firtree

SRCS = *.c \
	   src/*.c
all:
	@gcc $(SRCS) -o $(NAME) -g

clean:
	rm -f *.o

fclean: clean
	rm -f $(NAME)

re: fclean all